Controllers/DestiniesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Agencia_de_Viagens_App.Models;



namespace Agencia_de_Viagens_App.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class DestiniesController :ControllerBase
    {
        private readonly DataContext _context;

        public DestiniesController (DataContext context)
        {
            _context = context;
        }
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Destinies>>> GetDestinies()
        {
            return await _context.Jogos.ToListAsync();
        }

        [HttpGet("{id}")]
        public async Task<ActionResult<Destinies>> GetDestinies(int id)
        {
            var jogo = await _context.Destinies.FindAsync(id);

            if (Destinies == null)
            {
                return NotFound();
            }

            return Destinies;
        }
        // GET: Destinies
        public async Task<IActionResult> Index()
        {
            return View(await _context.Destiny.ToListAsync());
        }

        // GET: Destinies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destiny = await _context.Destiny
                .FirstOrDefaultAsync(m => m.id == id);
            if (destiny == null)
            {
                return NotFound();
            }

            return View(destiny);
        }

        // GET: Destinies/Create
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Destiny()
        {
            var destinies = _context.Destiny.ToList();
            return View(destinies);
        }

        public IActionResult Promotions()
        {
            var destinies = _context.Destiny.ToList();
            return View(destinies);
        }

        // POST: Destinies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,title,country,state,municipality,valueDaily,promotion")] Destiny destiny)
        {
            if (ModelState.IsValid)
            {
                _context.Add(destiny);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(destiny);
        }

        // GET: Destinies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destiny = await _context.Destiny.FindAsync(id);
            if (destiny == null)
            {
                return NotFound();
            }
            return View(destiny);
        }

        // POST: Destinies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,title,country,state,municipality,valueDaily,promotion")] Destiny destiny)
        {
            if (id != destiny.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(destiny);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DestinyExists(destiny.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(destiny);
        }

        // GET: Destinies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destiny = await _context.Destiny
                .FirstOrDefaultAsync(m => m.id == id);
            if (destiny == null)
            {
                return NotFound();
            }

            return View(destiny);
        }

        // POST: Destinies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var destiny = await _context.Destiny.FindAsync(id);
            _context.Destiny.Remove(destiny);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DestinyExists(int id)
        {
            return _context.Destiny.Any(e => e.id == id);
        }
    }
}

Controllers/UsersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Agencia_de_Viagens_App.Models;

namespace Agencia_de_Viagens_App.Controllers
{
    public class UsersController : Controller
    {
        private readonly Context _context;

        public UsersController(Context context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.User.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Recovery()
        {
            var users = _context.User.ToList();
            return View(users);
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,name,CPF,phone,email,password,administrator")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,name,CPF,phone,email,password,administrator")] User user)
        {
            if (id != user.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.User.FindAsync(id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.id == id);
        }
    }
}

Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Agencia_de_Viagens_App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Agencia_de_Viagens_App.styles.css" asp-append-version="true" />
</head>
<body>

    <header>
        <nav class="color navbar navbar-expand-md navbar-dark bg-dark text-center">

            <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Destinies" asp-action="Destiny">Destinos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Destinies" asp-action="Promotions">Promoções</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Contato</a>
                    </li>
                </ul>             
            </div>

             <div class="mx-auto order-0">
                 <a class="navbar-brand mx-auto" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/images/AmauriViagens.png" class="rounded-circle logo" alt="Logo">
                 </a>
             </div>   
      
            <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2 justify-content-end">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Users" asp-action="Create">Cadastrar Usuario</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Destinies" asp-action="Create">Cadastrar Destino</a>
                    </li>
                </ul>
            </div>

        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   <footer class="color border-top footer text-muted">
       <div class="container">
           &copy; 2022 - Desenvolvido por  - <a>Amauri Luiz</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/ValidationScriptsPartial.cshtml
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>