Models/Destiny.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace Agencia_de_Viagens_App.Models
{
    [Table("Destiny")]
    public class Destiny
    {
        [Key]
        public int id { get; set; }
        public string title { get; set; }
        [Required(ErrorMessage = "Informe o  País! ")]
        public string country { get; set; }
        [Required(ErrorMessage = "Informe Estado! ")]
        public string state { get; set; }
        public string municipality { get; set; }
        [Required(ErrorMessage = "Informe o valor da diária! ")]
        public double valueDaily { get; set; }
        public bool promotion { get; set; }
    }
}

Controllers/DestiniesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Agencia_de_Viagens_App.Models;



namespace Agencia_de_Viagens_App.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class DestiniesController :ControllerBase
    {
        private readonly DataContext _context;

        public DestiniesController (DataContext context)
        {
            _context = context;
        }
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Destinies>>> GetDestinies()
        {
            return await _context.Jogos.ToListAsync();
        }

        [HttpGet("{id}")]
        public async Task<ActionResult<Destinies>> GetDestinies(int id)
        {
            var jogo = await _context.Destinies.FindAsync(id);

            if (Destinies == null)
            {
                return NotFound();
            }

            return Destinies;
        }
        // GET: Destinies
        public async Task<IActionResult> Index()
        {
            return View(await _context.Destiny.ToListAsync());
        }

        // GET: Destinies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destiny = await _context.Destiny
                .FirstOrDefaultAsync(m => m.id == id);
            if (destiny == null)
            {
                return NotFound();
            }

            return View(destiny);
        }

        // GET: Destinies/Create
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Destiny()
        {
            var destinies = _context.Destiny.ToList();
            return View(destinies);
        }

        public IActionResult Promotions()
        {
            var destinies = _context.Destiny.ToList();
            return View(destinies);
        }

        // POST: Destinies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,title,country,state,municipality,valueDaily,promotion")] Destiny destiny)
        {
            if (ModelState.IsValid)
            {
                _context.Add(destiny);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(destiny);
        }

        // GET: Destinies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destiny = await _context.Destiny.FindAsync(id);
            if (destiny == null)
            {
                return NotFound();
            }
            return View(destiny);
        }

        // POST: Destinies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,title,country,state,municipality,valueDaily,promotion")] Destiny destiny)
        {
            if (id != destiny.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(destiny);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DestinyExists(destiny.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(destiny);
        }

        // GET: Destinies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destiny = await _context.Destiny
                .FirstOrDefaultAsync(m => m.id == id);
            if (destiny == null)
            {
                return NotFound();
            }

            return View(destiny);
        }

        // POST: Destinies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var destiny = await _context.Destiny.FindAsync(id);
            _context.Destiny.Remove(destiny);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DestinyExists(int id)
        {
            return _context.Destiny.Any(e => e.id == id);
        }
    }
}

Controllers/PackagesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Agencia_de_Viagens_App.Models;

namespace Agencia_de_Viagens_App.Controllers
{
    public class PackagesController : Controller
    {
        private readonly Context _context;

        public PackagesController(Context context)
        {
            _context = context;
        }

        // GET: Packages
        public async Task<IActionResult> Index()
        {
            return View(await _context.Package.ToListAsync());
        }

        // GET: Packages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var package = await _context.Package
                .FirstOrDefaultAsync(m => m.id == id);
            if (package == null)
            {
                return NotFound();
            }

            return View(package);
        }

        // GET: Packages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Packages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,origin,kids,adults,payment,dateGoing,dateReturn")] Package package)
        {
            if (ModelState.IsValid)
            {
                _context.Add(package);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(package);
        }

        // GET: Packages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var package = await _context.Package.FindAsync(id);
            if (package == null)
            {
                return NotFound();
            }
            return View(package);
        }

        // POST: Packages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,origin,kids,adults,payment,dateGoing,dateReturn")] Package package)
        {
            if (id != package.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(package);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PackageExists(package.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(package);
        }

        // GET: Packages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var package = await _context.Package
                .FirstOrDefaultAsync(m => m.id == id);
            if (package == null)
            {
                return NotFound();
            }

            return View(package);
        }

        // POST: Packages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var package = await _context.Package.FindAsync(id);
            _context.Package.Remove(package);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PackageExists(int id)
        {
            return _context.Package.Any(e => e.id == id);
        }
    }
}

Views/Destinies/Create.cshtml
@model Agencia_de_Viagens_App.Models.Destiny

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Destiny</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="title" class="control-label"></label>
                <input asp-for="title" class="form-control" />
                <span asp-validation-for="title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="country" class="control-label"></label>
                <input asp-for="country" class="form-control" />
                <span asp-validation-for="country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="state" class="control-label"></label>
                <input asp-for="state" class="form-control" />
                <span asp-validation-for="state" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="municipality" class="control-label"></label>
                <input asp-for="municipality" class="form-control" />
                <span asp-validation-for="municipality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="valueDaily" class="control-label"></label>
                <input asp-for="valueDaily" class="form-control" />
                <span asp-validation-for="valueDaily" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="promotion" /> @Html.DisplayNameFor(model => model.promotion)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Destinies/Delete.cshtml
@model Agencia_de_Viagens_App.Models.Destiny

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Destiny</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.state)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.state)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.municipality)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.municipality)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.valueDaily)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.valueDaily)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.promotion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.promotion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Destinies/Destiny.cshtml
@model IEnumerable<Agencia_de_Viagens_App.Models.Destiny>

@{
    ViewData["Title"] = "Destinos";
}

<div class="text-center color2">
    <h1 class="display-4">Destinos</h1>
    
    <form>
      <div class="form-group">
          <label for="inputState">Origem</label>
          <select id="inputState">
            <option>Acre</option>
            <option>Alagoas</option>
            <option>Amapá</option>
            <option >Amazonas</option>
            <option >Bahia</option>
            <option >Ceará</option>
            <option >Espírito Santo</option>
            <option >Goiás</option>
            <option >Maranhão</option>
            <option >Mato Grosso do Sul</option>
            <option >Minas Gerais</option>
            <option >Pará</option>
            <option >Paraíba</option>
            <option >Paraná</option>
            <option >Pernambuco</option>
            <option >Piauí</option>
            <option >Rio de Janeiro</option>
            <option >Rio Grande do Norte</option>
            <option >Rio Grande do Sul</option>
            <option >Rondônia</option>
            <option >Roraima</option>
            <option >Santa Catarina</option>
            <option >São Paulo</option>
            <option >Sergipe</option>
            <option >Tocantins</option>
            <option >Distrito Federal</option>
          </select>

           <label for="inputDate">Data Ida</label>
           <input id="dateGo" type="date">
    </div>

    <div class="form-group">
          <label for="inputState">Destino</label>
          <select id="inputState">
            <option >Acre</option>
            <option >Alagoas</option>
            <option >Amapá</option>
            <option >Amazonas</option>
            <option >Bahia</option>
            <option >Ceará</option>
            <option >Espírito Santo</option>
            <option >Goiás</option>
            <option >Maranhão</option>
            <option >Mato Grosso do Sul</option>
            <option >Minas Gerais</option>
            <option >Pará</option>
            <option >Paraíba</option>
            <option >Paraná</option>
            <option >Pernambuco</option>
            <option >Piauí</option>
            <option >Rio de Janeiro</option>
            <option >Rio Grande do Norte</option>
            <option >Rio Grande do Sul</option>
            <option >Rondônia</option>
            <option >Roraima</option>
            <option >Santa Catarina</option>
            <option >São Paulo</option>
            <option >Sergipe</option>
            <option >Tocantins</option>
            <option >Distrito Federal</option>
          </select>

            <label for="inputDate">Data Volta</label>
            <input id="dateBack" type="date">
      </div>

      <div class="form-group">
            <input type="submit" name="btnSubmit" class="btn" value="Pesquisar" />
       </div>  
    </form>
</div>

<div class="container">
    <div class="row">
        <div class="row row-cols-1 row-cols-md-2 g-4">
        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                
                    <div class="col">
                    <div class="card">
                      <img src="~/images/@(item.id).jpg"  class="card-img-top" alt="...">
                      <div class="card-body">
                        <h5 class="card-title">@item.title</h5>
                        <p class="card-text"> @item.country - @item.state - @item.municipality </p>
                        <h4 class="card-text"> Diária - R$ @item.valueDaily  </h4>
                        <a asp-controller="Packages" asp-action="Create" class="btn">Escolher opção</a>
                      </div>
                    </div>
                  </div>
               
            }
        }else{               
                    <div class="col">
                    <div class="card">
                      <img src="~/images/0.jpg"  class="card-img-top" alt="...">
                      <div class="card-body">
                        <h5 class="card-title">@Html.DisplayNameFor(model => model.title)</h5>
                        <p class="card-text">  @Html.DisplayNameFor(model => model.country) - @Html.DisplayNameFor(model => model.state) - @Html.DisplayNameFor(model => model.municipality) </p>
                        <h4 class="card-text"> Diária - R$  @Html.DisplayNameFor(model => model.valueDaily) </h4>
                      </div>
                    </div>
                  </div>
               
            }


         </div> 
    </div>
 </div>

Views/Destinies/Details.cshtml
@model Agencia_de_Viagens_App.Models.Destiny

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Destiny</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.state)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.state)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.municipality)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.municipality)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.valueDaily)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.valueDaily)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.promotion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.promotion)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Destinies/Edit.cshtml
@model Agencia_de_Viagens_App.Models.Destiny

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Destiny</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="title" class="control-label"></label>
                <input asp-for="title" class="form-control" />
                <span asp-validation-for="title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="country" class="control-label"></label>
                <input asp-for="country" class="form-control" />
                <span asp-validation-for="country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="state" class="control-label"></label>
                <input asp-for="state" class="form-control" />
                <span asp-validation-for="state" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="municipality" class="control-label"></label>
                <input asp-for="municipality" class="form-control" />
                <span asp-validation-for="municipality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="valueDaily" class="control-label"></label>
                <input asp-for="valueDaily" class="form-control" />
                <span asp-validation-for="valueDaily" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="promotion" /> @Html.DisplayNameFor(model => model.promotion)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Destinies/Index.cshtml
@model IEnumerable<Agencia_de_Viagens_App.Models.Destiny>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.state)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.municipality)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.valueDaily)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.promotion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.state)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.municipality)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.valueDaily)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.promotion)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Destinies/Promotions.cshtml
@model IEnumerable<Agencia_de_Viagens_App.Models.Destiny>

@{
    ViewData["Title"] = "Promoções";
}

<figure class="figure">

    <div class="container text-center">
        <h1 class="display-4">Promoções</h1>
        <div class="row">

            @if(Model != null) 
            {
                 @foreach (var item in Model){
                    @if (item.promotion)
                    {
                        <div class="card lg">
                          <img src="~/images/@(item.id).jpg"  class="img-fluid" alt="...">
                          <div class="card-body">
                            <h5 class="card-title">@item.title</h5>
                            <p class="card-text">@item.country - @item.state - @item.municipality</p>
                            <p class="card-text"><small class="text-muted">Diária - R$ @item.valueDaily  </small></p>
                            <a asp-controller="Packages" asp-action="Create" class="btn">Escolher opção</a>
                           </div>
                        </div>
                    }

            }
             }else{
                 <div class="card lg">
                      <img src="~/images/0.jpg"  class="img-fluid" alt="...">
                      <div class="card-body">
                       <h5 class="card-title"> @Html.DisplayNameFor(model => model.title)</h5>
                        <p class="card-text">  @Html.DisplayNameFor(model => model.country) - @Html.DisplayNameFor(model => model.state) - @Html.DisplayNameFor(model => model.municipality) </p>
                        <h4 class="card-text"> Diária - R$  @Html.DisplayNameFor(model => model.valueDaily) </h4>                   
                       </div>
                  </div>
             }


        </div>
    </div>

</figure>